### ISSUE TITLE
Verify OCE data conversion and metadata

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-siooc_data_transform#65] opened 2021-03-22 15:16 UTC
I found what I think is potentially an issue with the OCE package which is reading some BIO temperature data in IPTS-68 and claim to be in IPS-90 once ingested within the OCE package and outputted to the JSON file. There's a potential that the data was really converted to IPS-90. 

Here are few steps to do:
- [x] Compare OCE data vs data read by the tool within the cioos_data_transform.utils.odf.read (no conversion with this one)
- [x] Is there other parameters that have the same issue (likely not but will be hard to find)
- [x] Create an issue in the OCE package repository

**Comment by JessyBarrette** [comment] 2021-03-22 18:58
No conversion was observed within our test files. This suggests that the OCE TEMP data which is originally in IPTS-68 is not converted to ITS-90 even though OCE suggests that the ingest data has an ITS-90 scale.

**Comment by JessyBarrette** [comment] 2021-03-22 18:59
Time variables SYTM_01 are modified by the OCE package and are replaced by a constant value.

**Comment by richardsc** [comment] 2021-03-31 16:34
Hi @JessyBarrette -- I'm one of the `oce` developers (and I work at BIO). 

Can you provide details on this and post at the `oce` Issues page? Unfortunately if this does turn out to be a bug, we *just* resubmitted to CRAN last week to fix some other issues, so this won't get updated (on CRAN at least) until we prepare a 1.5 release (which likely won't be for a few months).

**Comment by JessyBarrette** [comment] 2021-03-31 16:43
Oh Hi @richardsc  yeah sorry I'm meant to send a few issues we found like that on the OCE issue page. :) Will definitely do it! I'm a bit submerged with work these days with the end of the fiscal year. I'm actually just about to run a little script I made to compare the OCE parsed data from the ODF to another python parsing script I made. Should be helpful to detect any differences :)

**Comment by richardsc** [comment] 2021-03-31 17:07
That would be great.

Ideally you can provide a reprex (reproducible example) that shows what the differences are. There are a lot of years of work handling all kinds of different ODF quirks that are built into the `read.odf()` in `oce`, but as we discovered it's impossible to be able to programmatically handle all of them (because ultimate a lot of ODF files are hand-edited and or hand-made).

Some other differences may be due to conventions, e.g. in `oce` we almost always convert time formats to be in "POSIX" time, e.g. seconds since 1970-01-01 UTC, rather than store whatever crazy time was in the ODF file (character time, julian days, etc)

**Comment by richardsc** [comment] 2021-04-09 00:32
Hi @JessyBarrette -- I think this is fixed now in `oce` at the above-linked issue. Thanks for the catch!

Unfortunately as we *just* submitted to CRAN this fix probably won't make it into a new CRAN version for at least a couple of months. In the meantime, you'll have to build from source using the development version on Github. The easiest[^1] way to do that is to use the `remotes` package to install straight from Github:
```
remotes::install_github("dankelley/oce", ref="develop")
```

[^1]: "easy" is a relative term, depending on your operating system, and whether you are set up to build R packages from source. For Windows all you should need to do is install [Rtools](https://cran.r-project.org/bin/windows/Rtools/). For OSX you'll need the command line developer tools installed. For Linux you'll need all the external dependencies as well as the compilers -- I recently wrote up a guide for Ubuntu which you can find [here](https://github.com/dankelley/oce/wiki/Configuring-a-Linux-Mint-20-system-to-be-able-to-build-oce-from-source)

**Comment by richardsc** [comment] 2021-04-09 00:43
I would also point out (since it tricked me for a while even though I probably had a hand in writing the code and I most certainly was involved in the concept) that the behaviour when you use the `[[` accessor on an `oce` object to extract a field depends on the field. In the case of `temperature`, the `[[` function will extract the temperature as T90 even if the temperature stored in the object is T68. To get the value stored in the object in the original units you have to access it directly, e.g.

``` r
library(oce)
odf <- read.odf(system.file("extdata", "CTD_BCD2014666_008_1_DN.ODF.gz", package="oce"))
plot(odf[['temperature']] - odf@data$temperature)
```
```
Warning message:
In read.odf(system.file("extdata", "CTD_BCD2014666_008_1_DN.ODF.gz",  :
  "CRAT_01" should be unitless, but the file states the unit as "S/m" so that is retained in the object metadata. This will likely cause problems.  See ?read.odf for an example of rectifying this unit error.
```
![image](https://user-images.githubusercontent.com/233584/114112743-62dab380-98b3-11eb-9017-ffbedc3808ed.png)
<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JessyBarrette** [comment] 2021-04-12 20:58
@richardsc that's good to know! I'm unfortunately not too familiar with OCE package and R language. We are using right OCE to test our conversion of the ODF files to NetCDF in python.  

I found out that the issue listed with the SYTM variables was associated to the conversion we were doing from OCE object to json to compare both in a python environment.

I found two smaller other issues that I'll share with you on the OCE repo hopefully today!

**Closed** 2023-03-13 18:14 UTC
