### ISSUE TITLE
Review of converted NetCDF files

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-siooc_data_transform#27] opened 2021-02-12 01:47 UTC
The OCE package seems to be the preferred way to convert the ODF files to NetCDF. However, another simple way would be to just parse the ODF header format and data directly by using a simple method like described [here](https://gist.github.com/JessyBarrette/4e197b6a39c6207a340a01b18c59ab93). 

This method essentially parses the ODF header into a list of dictionaries. 
Data can then be easily converted to a python pandas dataframe and python xarray dataset. Original attributes from the ODF format can be easily carried on to the xarray dataset which can be saved to a nc file easily.

**Comment by pramod-thupaki** [comment] 2021-02-12 01:51
Duplicate of #26

**Closed** 2021-02-12 03:02 UTC
